// Curated list of Greater Accra areas. Listings and search are restricted to
// these values instead of free text, so location data stays clean and
// filterable instead of "Accra", "ACCRA", "accra area" etc. all meaning the
// same thing but never matching each other.
export const ACCRA_LOCATIONS: string[] = [
  "Abeka",
  "Abelemkpe",
  "Ablekuma",
  "Achimota",
  "Adabraka",
  "Adenta",
  "Adjiringanor",
  "Afienya",
  "Airport Residential Area",
  "Airport West",
  "Ashaiman",
  "Ashaley Botwe",
  "Ashongman",
  "Ashongman Estates",
  "Asylum Down",
  "Awoshie",
  "Baatsona",
  "Bubuashie",
  "Cantonments",
  "Chorkor",
  "Dansoman",
  "Darkuman",
  "Dodowa",
  "Dome",
  "Dzorwulu",
  "East Airport",
  "East Legon",
  "Gbawe",
  "Haatso",
  "James Town",
  "Kaneshie",
  "Kasoa",
  "Kokomlemle",
  "Kwabenya",
  "Kwashieman",
  "La",
  "Labadi",
  "Labone",
  "Lapaz",
  "Ledzokuku",
  "Legon",
  "Madina",
  "Mallam",
  "Mamprobi",
  "Manet",
  "McCarthy Hill",
  "Nima",
  "North Kaneshie",
  "North Legon",
  "North Ridge",
  "Nungua",
  "Odorkor",
  "Ofankor",
  "Osu",
  "Pokuase",
  "Prampram",
  "Ridge",
  "Roman Ridge",
  "Sakumono",
  "Santa Maria",
  "Sowutuom",
  "Spintex",
  "Taifa",
  "Tantra Hill",
  "Tema Community 1",
  "Tema Community 2",
  "Tema Community 4",
  "Tema Community 6",
  "Tema Community 8",
  "Tema Community 9",
  "Tema Community 25",
  "Tema Newtown",
  "Teshie",
  "Tesano",
  "Trasacco",
  "Ussher Town",
  "Weija",
  "West Legon",
].sort();
